### ISSUE TITLE
Matrice - 19 formulaires de segmentations saisis,enregistréset envoyés sans impact sur matrice

### ISSUE THREAD

**Issue by kkhider** [akqira/RepRep#101]
![image](https://user-images.githubusercontent.com/41648667/48708673-7cf09a00-ec03-11e8-9b50-2dfc9c77c658.png)

**Comment by kkhider** [comment]
![image](https://user-images.githubusercontent.com/41648667/48708741-af01fc00-ec03-11e8-8013-8c308b03b836.png)

**Comment by akqira** [comment]
fixed
