### ISSUE TITLE
Questionnaire de segmentation

### ISSUE THREAD

**Issue by kkhider** [akqira/RepRep#102]
une fois le questionnaire complété enregistré et envoyé il est noté comme étant Modifié . OK mais quandje reclique dessus je peux retoucher au questionnaire re enregistré et re envoyé. Or , si le questionnaire est Envoyé on ne peut plus le modifier pour ne pas alterner les données matrice

**Comment by kkhider** [comment]
Pour la démo c'est ok , ca ne me causera pas de souci - cette requete est pour l'efficacité de l'outils chez le client

**Comment by akqira** [comment]
fixed
