### ISSUE TITLE
Fréquence des Visites - Changement de Cycle

### ISSUE THREAD

**Issue by kkhider** [akqira/RepRep#12]
Définition des fréquences à chaque cycle , chaque début de cycle refaire les fréquences ou bien hériter des anciens - Cependant, NON AUTORISE à changer les fréquences pendant un cycle. résultats monitoring et surtout objectifs Calls correspondant aux fréquences initiales

**Comment by akqira** [comment]
double du ticket #21 et #11 
Le process de fermeture de cycle sera détaillé dans un document PDF qui contient tous les process application que je metterai en place
