### ISSUE TITLE
Accès au rapport dernière visite

### ISSUE THREAD

**Issue by kkhider** [akqira/RepRep#29]
Liste des RDV en bleu dans Agenda - Clique sur un PM et accès au rapport de visite - Capitale fonctionnalité à montrer aux prospects en Démo commerciale

**Comment by akqira** [comment]
Il faut que toi ou moi on saisi des rapports antérieurs pour qu'ils soient visibles tel que souhaité

**Comment by kkhider** [comment]
GitHub est un outils extra ; j'allais soulevé ce problème et je reviens sur les issues pour comprendre que ca n'en est pas un probleme en fait
