### ISSUE TITLE
Options dans Admin Interface- Sectorisation

### ISSUE THREAD

**Issue by kkhider** [akqira/RepRep#34]
C'est fonctionnel pour la version Beta ou bien version 2 ??? Je constate que c'est inactif (non fonctionnel)

**Comment by akqira** [comment]
Pour la version 2 nchallah

**Comment by kkhider** [comment]
Ok mais en cas d'ajout de secteur et sous secteur pouvons nous gérer cela à notre niveau en attendant que la version 2 soit opérationnelle ? ca risque d'arriver les ajouts secteur sous secteurs

**Comment by akqira** [comment]
d'après tes dires, la modification des secteurs et/ou sous secteurs reste rare mais possible. Donc on avais pris la décision si tu te rappelle de gérer ça manuellement coté coulisses en attendant de faire ça dans une version 2

**Comment by kkhider** [comment]
ok ca marche , j'informerai le client dans le cadre de la présentation
