### ISSUE TITLE
Segmentation Matricielle 

### ISSUE THREAD

**Issue by kkhider** [akqira/RepRep#35]
Les matrices des interfaces Superviseurs sont identiques à la matrice globale Admin ce qui n'est pas logique !! chaque Superviseur a normalement sa propre matrice correspondant au positionnement des PM de ses secteurs sur la Matrice . Question, pourquoi avons nous des matrices identiques ??? Ni la démo et encore moins la version client ne doit afficher ces résultats

**Comment by akqira** [comment]
fixed
