### ISSUE TITLE
Définition de fréquence

### ISSUE THREAD

**Issue by kkhider** [akqira/RepRep#36]
Quand nous définissons une fréquence la fréquence qui apparaît par défaut est zéro quel que soit la fréquence réelle . Or la fréquence qui apparaît devrait être celle définie au préalable .

Aussi , en définissant une nouvelle fréquence parfois il arrive que le système ne calcul pas PM*Fq ( Bug)

**Comment by akqira** [comment]
Je viens de tester en changeant de frequence a tous le monde, or je n'arrive pas a reproduire le bug. @kkhider  Est ce que tu peux inclure une capture d'ecran dans ce fil de disucssion
Regarde la photo que j'ai joint pour que tu sache comment faire

![capture](https://user-images.githubusercontent.com/28217846/44663135-f6fff100-aa0f-11e8-8762-cf81ef41cd22.PNG)

**Comment by kkhider** [comment]
![image](https://user-images.githubusercontent.com/41648667/44672351-77cae700-aa28-11e8-9992-4e1f4dbb2350.png)

**Comment by kkhider** [comment]
ca arrive 1 fois sur 8 , la fréquence définie est 2 dans cet exemple

**Comment by kkhider** [comment]
Normalement si un médecin est à fréquence 1 si je selectionne la fréquence je devrais avoir 1 . Je change à 2 , je valide, si je reviens vers sa fréquence elle est à 2 . Si je souhaite ne pas voir le médecin au prochain cycle je selectionne 0 si je reviens vers sa fréquence j'ai 0. Conclusion, l'onglet fréquence doit nous donner la fréquence actuelle réelle

**Comment by akqira** [comment]
Ce cas de figure ne pose pas de problème et peut être implémenté. L'exception qui pose problème c'est le fait qu'un SFE puisse définir la fréquence de visite de plusieurs médecins en même temps en tenant compte des filtre, par exemple : Tous les MG du secteur x de typologie cabinet, si nous avons 20 médecins touchés et qu'on clique sur définir fréquence, imagine si ces médecins n'ont pas tous la même fréquence actuelle.
Une idée ??

**Comment by kkhider** [comment]
ah mais oui tout à fait !!!! tu as raison ! on annule donc l option et on traite juste le bug !!! merci pour ta virulence :) 


Envoyé depuis mon smartphone Samsung Galaxy.
-------- Message d'origine --------De : Abdelkader KEBIR <notifications@github.com> Date : 28/08/2018  14:03  (GMT+01:00) À : akqira/RepRep <RepRep@noreply.github.com> Cc : kkhider <karinakhider@gmail.com>, Assign <assign@noreply.github.com> Objet : Re: [akqira/RepRep] Définition de fréquence (#36) 
Ce cas de figure ne pose pas de problème et peut être implémenté. L'exception qui pose problème c'est le fait qu'un SFE puisse définir la fréquence de visite de plusieurs médecins en même temps en tenant compte des filtre, par exemple : Tous les MG du secteur x de typologie cabinet, si nous avons 20 médecins touchés et qu'on clique sur définir fréquence, imagine si ces médecins n'ont pas tous la même fréquence actuelle.

Une idée ??

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/akqira/RepRep","title":"akqira/RepRep","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/akqira/RepRep"}},"updates":{"snippets":[{"icon":"PERSON","message":"@akqira in #36: Ce cas de figure ne pose pas de problème et peut être implémenté. L'exception qui pose problème c'est le fait qu'un SFE puisse définir la fréquence de visite de plusieurs médecins en même temps en tenant compte des filtre, par exemple : Tous les MG du secteur x de typologie cabinet, si nous avons 20 médecins touchés et qu'on clique sur définir fréquence, imagine si ces médecins n'ont pas tous la même fréquence actuelle.\r\nUne idée ??"}],"action":{"name":"View Issue","url":"https://github.com/akqira/RepRep/issues/36#issuecomment-416575815"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/akqira/RepRep/issues/36#issuecomment-416575815",
"url": "https://github.com/akqira/RepRep/issues/36#issuecomment-416575815",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [akqira/RepRep] Définition de fréquence (#36)",
"sections": [
{
"text": "",
"activityTitle": "**Abdelkader KEBIR**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@akqira",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"akqira/RepRep\",\n\"issueId\": 36,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"akqira/RepRep\",\n\"issueId\": 36\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/akqira/RepRep/issues/36#issuecomment-416575815"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 372707583\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by akqira** [comment]
Fixed
