### ISSUE TITLE
Filtre Rep non fonctionnel - Niveau 1 - Monitoring 

### ISSUE THREAD

**Issue by kkhider** [akqira/RepRep#37]
![image](https://user-images.githubusercontent.com/41648667/45038340-5342c080-b061-11e8-831a-812138bc706c.png)

**Comment by kkhider** [comment]
A savoir qu'il s'agit de l'interface Superviseur et non pas Rep - A quoi sert le filtre ?

**Comment by akqira** [comment]
Ce filtre n'a pas lieu d'etre ici. Je le supprime.
Fixed
