### ISSUE TITLE
Version PC Niveau 2 - Matrice 

### ISSUE THREAD

**Issue by kkhider** [akqira/RepRep#38]
La matrice de la version PC a disparue ; Nous sommes d'accord que la matrice n'a pas lieu d'etre ajoutée dans la version mobile. Mais dans la version pc du superviseur elle est importante .

**Comment by akqira** [comment]
C'est fonctionnelle, je viens de verifier, je dois donc tester sur ton PC

**Comment by akqira** [comment]
Je cloture
