### ISSUE TITLE
Accès Agenda - Version mobile superviseur

### ISSUE THREAD

**Issue by kkhider** [akqira/RepRep#39]
On avait décidé que la version mobile serait allégée et ne contiendrait que des nécessaires au travail sur terrain à savoir : tableau de bord global par rep et accès sythèse agenda ; or je ne trouve pas l'accès agenda dans ma version mobile

**Comment by kkhider** [comment]
révision aujourdhui de ce point

**Comment by akqira** [comment]
Je viens de vérifier ce point. Tout marche comme demandé, étapes pour reproduire : 
1. Accès à l'application mobile en tant que superviseur
2. Cliquer sur Monitoring
3. Cliquer sur un REP on accède direct à la synthése de son agenda par jour, on peut changer le filtre date pour accéder aux autres journées.
Voir pièces jointes
![1](https://user-images.githubusercontent.com/28217846/46554760-95ba2000-c8e1-11e8-85f8-c4307d628833.PNG)
![2](https://user-images.githubusercontent.com/28217846/46554761-95ba2000-c8e1-11e8-8f64-05fe65488f88.PNG)
