### ISSUE TITLE
Protocole début et fin de cycle - Clarification 

### ISSUE THREAD

**Issue by kkhider** [akqira/RepRep#41]
Bonjour :) Question concernant le protocole Cycle début et fin - Le cycle de la version démo se clôture le 15 Septembre - J'ai modifié la date de mon PC ce matin au 15 Septembre - Donc monitoring vide c'est à dire que le protocole ne considère pas la date de fin mais plutot je jour avant - Est ce fait intentionnellement ? si oui, pourquoi ? et aussi est ce que le calcul du nombre de jours travaillés prends en compte que le dernier jour n'est pas pris en compte ? Dans la version démo le 15 Septembre est un samedi donc non travaillé de toute facon . Aussi, ne serait il pas plus simple de clôturer le 15 Septembre à une heure précise 21h exemple ?

**Comment by akqira** [comment]
Pour la date clôture le système utilise non seulement la date mais aussi l'heure, le format d'une date est le suivant : 15 Septembre 2018 00:00
Donc s'il n'a pas inclut le dernier jour c'est qu'il y a un adjustement à faire de ma part en spécifiant l'heure. Pour la deuxième tranche de la question, je pense que oui, ça serait intéressant pour nous de dire qu'il clôture en spécifiant et la date et l'heure, ce qui règle aussi le problème précedant...

Je vais donc ajouter cette option

**Comment by kkhider** [comment]
fixed? update

**Comment by akqira** [comment]
Fixed. Maintenant le dernier jour du cycle entre dans le calcul monitoring
