### ISSUE TITLE
Export vers Excel ne fonctionne pas

### ISSUE THREAD

**Issue by kkhider** [akqira/RepRep#42]
Export option non fonctionnel + n'existe pas dans monitoring rep ce qui est dommage 
![image](https://user-images.githubusercontent.com/41648667/45810988-46aea100-bccc-11e8-8f95-f240ae191db8.png)

**Comment by kkhider** [comment]
Fixed ?? si oui , mise à jour démo? merci

**Comment by akqira** [comment]
Fixed
