### ISSUE TITLE
Les WE - Mise au point

### ISSUE THREAD

**Issue by kkhider** [akqira/RepRep#43]
WE Tunisie : Samedi - Dimanche
WE Algérie : Vendredi - Samedi
WE Maroc et Afrique : Samedi - Dimanche

**Comment by akqira** [comment]
Cette fonctionnalité existe déjà. InitialementChaque SFE peut configurer son weekend dans la fenêtre Options comme indiqué ci dessous. 


![we](https://user-images.githubusercontent.com/28217846/46249349-e46e4280-c427-11e8-9399-d205853d9d21.PNG)
