### ISSUE TITLE
Bug ouverture Campagne de Segmentation 

### ISSUE THREAD

**Issue by kkhider** [akqira/RepRep#44]
Impossible de valider l'action ci-dessous 

![image](https://user-images.githubusercontent.com/41648667/46403698-8da48980-c703-11e8-89fb-bad76f0d0eaf.png)

**Comment by akqira** [comment]
Campagne ne passe pas a cause du cycle indéfini. (Ancienne version fallait les lier avec fréq du cycle en cours), maintenant la campagne n'a rien n'avoir avec les fréquences de visites ni les cycles.

Donc fixed now

**Comment by kkhider** [comment]
OK compris
