### ISSUE TITLE
Calendrier de planification 

### ISSUE THREAD

**Issue by kkhider** [akqira/RepRep#46]
Le calendrier d'affectation des médecins dans le module planification Rep n'est pas correcte . Les WE que j'ai défini dans le cycle sont Samedi Dimanche - L'interface Rep planif est restée figée à WE Samedi Vendredi . Donc je ne peux pas planifier correctement - Question : normalement le calendrier s'adapte ? Si ce n'est pas le cas , donner au rep un calendrier ouvert ( inclus tous les jours de la semaine ) . Ce n'est qu'une proposition . Ceci étant , le calendrier tel quel n'est pas bon 

![image](https://user-images.githubusercontent.com/41648667/46408175-87b5a500-c711-11e8-9e81-78f84697edc1.png)

**Comment by akqira** [comment]
Après investigations voici la réponse: 
On a problème en deux parties. 
1. Partie une : 
Le fait que tu n'arrive pas à voir les deux autres jours c'est juste a cause de la taille de l'écran mobile, il faut donc juste glisser vers la droite pour les voir, la preuve sur ta capture d'écran on voit bien qu'il manque le boutton fermer du calendrier qui est donc tout à droite.
Solution à ce problème : Comme il n'est pas possible de jour sur ce détail là, on propose au REP de faire pivoter son écran pour avoir toutes les colonnes de la semaine. Voir image attachée.

2. Partie deux : 
Pour que la partie 1 fonctionne il faut imposer un minimum requis pour la taille des écrans mobiles, cette régle va faire en sorte qu'on se couvre vis à vis de la fonctionnalité sur mobile, tu veux planifier en mobile, faut avoir un minimum de tant ...

J'attends ton feedback; si tu veux qu'on skype pour meilleur explication je suis OK
![1](https://user-images.githubusercontent.com/28217846/46438171-76928580-c75d-11e8-8b4d-8cdd527e3ac1.PNG)
![2](https://user-images.githubusercontent.com/28217846/46438172-76928580-c75d-11e8-9d5b-3a918d2f62f0.PNG)

**Comment by kkhider** [comment]
je confirme ! c'est un souci d'affichage que je vais devoir signaler en formation - j'ai planifier les visites . 

Par ailleurs, j'ai constaté qu'il est possible pour un REP de planifier des rdv meme sur des joursfériés. Ce n'est absolument pas un problème . Ce qui est impératif c'est le calcul monitoring qui dont prendre en compte les jours fériés pour total objectifs ( performance) Call ( PM*Fq). Tu confirmes ?????

**Comment by akqira** [comment]
Je confirme que le rep peut planifier par erreur une date férié. Celà ne rentre pas en considération dans le monitoring donc c comme si il n'y pas de rdv ni même de rapport de visite.
Cela dit, je ferai en sorte quand j'aurai du temps de rentre même cette fenêtre intelligente et bloquer le choix d'un jour férié dans la planif ainsi que les weekends.
Je bascule cet issue dans le milestone version 2 pour le moment

**Comment by kkhider** [comment]
Fixed de mon coté and I thank you for that
