### ISSUE TITLE
Signalisation des listes rapports de visites à effectuer introuvable

### ISSUE THREAD

**Issue by kkhider** [akqira/RepRep#47]
j'ai 5 rapports à saisir normalement non signalés 
![image](https://user-images.githubusercontent.com/41648667/46408396-538eb400-c712-11e8-8ad4-40ef815c809f.png)

**Comment by kkhider** [comment]
je me suis déconnectée et re connectée pour tester et résultat négatif

**Comment by kkhider** [comment]
opération effecutée sur 2 ème rep et toujours pas liste rapports

**Comment by kkhider** [comment]
point important pour évaluer l'erreur ; le cycle commence le 04 Octobre - j'ai avancé mon ordinateur d'un jour pour s'aligner au début de cycle - par contre mon portable est au 03 Octobre - peut etre que c'est pour cela que je n'ai pas de liste rapports . Par ailleurs, la liste sur agenda est signalée en rouge ( donc visites effectuées censées)

**Comment by akqira** [comment]
C'est logique. Et c'est donc pas un bug. Explication : 
Ton PC = le serveur (futur ça deviens azure notre serveur), donc la date PC du serveur est utilisée pour effectuer le calcul des RDV qui sont dans le passé et sans rapport. 
Tes rdv sont effectués le 3 Octobre, et le cycle commence le 04 Oct. Le système te laisse voir dans le calendrier les rdv hors cycle, mais ne les prend pas en compte.
A mon avis il serait plus logique de faire en sorte que dans le calendrier global, on restreint les rdv du cycle en cours pour pas créer de confusion comme mnt

T'en penses quoi ??

**Comment by kkhider** [comment]
Kaki peux tu traiter ce point en urgence . Je ne peux pas faire de rapports - la présnetation coloplast peut se décider a tout moment

**Comment by akqira** [comment]
On skype pour que je puisse voir sur ton PC direct. 20h Ok pour toi ?

**Comment by kkhider** [comment]
ok

**Comment by akqira** [comment]
fixed
