### ISSUE TITLE
Synthèse hebdomadaire visites ne prend pas en compte le début du cycle

### ISSUE THREAD

**Issue by kkhider** [akqira/RepRep#48]
ci-dessous la synthèse hebdomadaire de visites ne prend pas en compte le début du cycle à savoir le 04 Octobre
![image](https://user-images.githubusercontent.com/41648667/46533363-9aacae80-c8a4-11e8-9eb6-3e3a6921a829.png)

**Comment by akqira** [comment]
Bug confirmé et fixé
