### ISSUE TITLE
Efficacité Clic sur les rdv dans agenda - version mobile Supervieur

### ISSUE THREAD

**Issue by kkhider** [akqira/RepRep#49]
c'est pas evident d'afficher le rapport visite via agenda pour le superviseur ; obligé de cliquer plusieurs fois pour avoir la fiche visualisée ;

**Comment by akqira** [comment]
Je viens de tester. L'accès se fait  avec un double clique et non pas un seul clique. Que ça soit la version mobile ou Desktop. Faut cliquer DEUX fois rapidement ou TAPPER deux fois rapidement dépend le terminal d'accès
