### ISSUE TITLE
Question sur l'état d'avancement

### ISSUE THREAD

**Issue by kkhider** [akqira/RepRep#50]
Je suis sur Interface Superviseur Mahdaoui dont j'ai réalisé des rapports de visite en tant que rep.
Sur monitoring les chiffres sont bons - sauf pour 57% ( en haut de page) : à quoi correspond ce chiffre ? Si je calcul la moyenne performance de toute l'équipe de Mahdaoui ( performance des 2 resp) j’obtiens 58,6%  
![image](https://user-images.githubusercontent.com/41648667/46541338-0a7a6380-c8bc-11e8-8fb2-89fe9de9e167.png)

**Comment by akqira** [comment]
Pas un bug, mais un arrondi de calcul. Explications : 
Regarde cette capture de mon ecran, 
Pour la première ligne : le calcul donne = 38 / 66 = 0,5757575757575758  ce qui est arrondi a 58% 
Pour la deuxieme ligne le calcul donne = 62 / 66 =  0,9393939393939394 ce qui est arrondi a 94%

Le vrai taux d'avancement global se calcul donc  
0,5757575757575758 + 0,9393939393939394 / 2 = 0,7575757575757576
Et la aussi on arrondi a 75%
Donc pour dire que l'arrondi parfoi est un chiffre plus haut parfois non. On peut garder les chiffre avec virgule mais un avancement affiché 74,32 % par exemple n'est pas significatif a mon avis.
A toi d'en décider , je cloture le issue
![1](https://user-images.githubusercontent.com/28217846/46555309-2cd3a780-c8e3-11e8-82ca-0ebfd8e5d5df.PNG)

**Comment by kkhider** [comment]
Interface Mahdaoui Superviseur , barre affiche 50% ? Or dans Interface Admin quand je vais dans monitoring Mahdaoui la barre d'état d'avancement affiche 25 % . D'ou viennent ces taux ? Quelle est la formule sur l'appli ??? A savoir qu'il n'est pas logique d'avoir 2 états d'avancements différents sur un meme superviseur ( 1 sur ADMIN et l'autre sur l'interface meme du superviseur)
![image](https://user-images.githubusercontent.com/41648667/46658281-a523bc80-cbb2-11e8-8f99-571169b35297.png)
![image](https://user-images.githubusercontent.com/41648667/46658453-0a77ad80-cbb3-11e8-8b35-a87f6e361edc.png)
