### ISSUE TITLE
Rep Othamani - Bug au niveau saisie rapports 

### ISSUE THREAD

**Issue by kkhider** [akqira/RepRep#51]
![image](https://user-images.githubusercontent.com/41648667/46619868-81fdfc00-cb23-11e8-9eb5-d8b49daefc7e.png)
![image](https://user-images.githubusercontent.com/41648667/46619888-8de9be00-cb23-11e8-82ff-cc91664b8c50.png)
![image](https://user-images.githubusercontent.com/41648667/46619918-9f32ca80-cb23-11e8-84f3-f8f6b97cb7ce.png)

**Comment by kkhider** [comment]
aucune réponse quant à ce bug; merci de donner suite

**Comment by akqira** [comment]
Bug fixed.
