### ISSUE TITLE
Monitoring - Fenêtres Inaccessibles 

### ISSUE THREAD

**Issue by kkhider** [akqira/RepRep#52]
Je ne peux pas accéder à Performance Spécialité 
![image](https://user-images.githubusercontent.com/41648667/46663654-f639ad80-cbbe-11e8-8186-87230193a5b6.png)

**Comment by kkhider** [comment]
Réponse ?

**Comment by akqira** [comment]
Bug fixed

**Comment by kkhider** [comment]
Great , on peut prévoir donc la mise à jour sur mon pc pour les besoins Démo - à prévoir pour le WE à savoir vendredi ou samedi prochain ; merci
