### ISSUE TITLE
Liste rapports

### ISSUE THREAD

**Issue by kkhider** [akqira/RepRep#55]
Rep Boudiba , j'ai 33 Rapports à faire mais qui ne s'affichent pas sur l'interface du Rep ou s'affiche avec interface planification !!!!!!!!! La démo n'est pas fiable pour etre présentée auprès du client tel quel . Merci pour ta réactivité . Ca devient très inquiétant comme situation et le risque de tout perdre augmente malheureusement

**Comment by akqira** [comment]
Besoin de plus d'informations pour reproduire a mon niveau.
1. Date que tu as pris pour tester
2. Quelle interface ? comment tu as su que tu as 33 rapports si tu n'arrive pas  a y acceder ?
3. Est ce que tu vois le chiffre 33 sur la barre laterale gauche et en cliquant il ne se passe rien ou bien tu l'a deduit par l'agenda ??

L'ideal serait d'accompagner par des captures d'ecran pour m'aider a agir vite

**Comment by kkhider** [comment]
1- Date mise à jour 
2- tel précisé, interface rep Boudiba sur modible - 33 rapports evidement identifiés via agenda
3- le chiffre 33 sur la barre n'apparait que furtuvement ( 1 seconde puis disparait) . As tu testé de ton coté ? 

merci pour tes réponses

**Comment by kkhider** [comment]
je viens de constaté que ce bug n'apparait que dans la version mobile et pas sur version pc

**Comment by akqira** [comment]
Impossible de reproduire l'erreur à mon niveau. J'ai attaché des "Captures d'écran" (ce qu'il faut toujours faire) pour voir confirmer que ça ne bug pas 
Deux interfaces, mobiles et écran, 35 rapports à saisir, aucun bug
![issue55img3](https://user-images.githubusercontent.com/28217846/46970553-bb051600-d0b9-11e8-918e-ac0b287bad6c.PNG)

![issue55img1](https://user-images.githubusercontent.com/28217846/46970509-99a42a00-d0b9-11e8-864e-f5b069e645c8.PNG)
![issue55img2](https://user-images.githubusercontent.com/28217846/46970510-99a42a00-d0b9-11e8-92a0-f10efb1cd986.PNG)
