### ISSUE TITLE
Base de données - New feauture

### ISSUE THREAD

**Issue by kkhider** [akqira/RepRep#56]
Ajout nouveau médecin est à inclure dans la partie base de données interface Rep . Elle devra faire l'objet d'une validation pour les changements opérés dans les fiches médecins . Combien penses tu que cette opération ^prendre a etre mise en place ? Nous avons bien négligé ce point important en plus ajout et suppression secteurs sous secteurs 

![image](https://user-images.githubusercontent.com/41648667/46957645-44a3ec00-d098-11e8-9861-c256442b6e2f.png)

**Comment by akqira** [comment]
Je vais faire une estimation de ces ajouts une fois que je fini les autres issues

**Comment by akqira** [comment]
feature added
