### ISSUE TITLE
Bug Ajout nouveau PM interface Admin

### ISSUE THREAD

**Issue by kkhider** [akqira/RepRep#57]
Interface Admin ; après validation d'ajout d'un nouveau PM petit bug ci-dessous que j'ai souvent vu après création d'une nouvelle fonctionnalité - Ajustement je pense , 
![image](https://user-images.githubusercontent.com/41648667/47354594-68ca8300-d6bf-11e8-8bef-1538069a3d22.png)

**Comment by kkhider** [comment]
![image](https://user-images.githubusercontent.com/41648667/47354675-9d3e3f00-d6bf-11e8-8ea3-db00962f664f.png)

**Comment by kkhider** [comment]
![image](https://user-images.githubusercontent.com/41648667/47354718-b6df8680-d6bf-11e8-9f8a-04553dc602f4.png)

**Comment by kkhider** [comment]
J'ai ajouté le code médecin ( juste un numéro) et l'enregitrement est passé mais revenu vers bug ( première capture d'écran . Donc option code PM obligatoire dans interface Admin ( ok) mais bug persiste

**Comment by akqira** [comment]
will be fixed today

**Comment by akqira** [comment]
fixed
