### ISSUE TITLE
Rep interface - Ajout nouveau Médecin - Choix des secteurs à limiter à ceux du Rep

### ISSUE THREAD

**Issue by kkhider** [akqira/RepRep#58]
Interface Rep ( Sonia Kabaa) secteur Alger - Ajout nouveau PM , dans choix secteur j'ai également le secteur d'Oran - Comme pour filtre Base de données , je ne devrait pas avoir autre secteur que ceux du Rep en question - Récap : Ajout secteurs et sous secteurs c'est à notre niveau ( pour l'instant) or, ajout nouveau PM qui se fait par les Rep ( notamment) sur terrain ( découverte d'un nouveau PM sur terrain). Un Rep ajoute un Nouveau PM découvert sur ces secteurs - Limiter le filtre à secteurs du Rep
![image](https://user-images.githubusercontent.com/41648667/47355237-21dd8d00-d6c1-11e8-9d94-fcaa356dc49b.png)

**Comment by kkhider** [comment]
Je suis allée sur Admin pour approuver l'ajout PM est bug 
![image](https://user-images.githubusercontent.com/41648667/47355772-877e4900-d6c2-11e8-8d5c-98217f0a9d4d.png)

**Comment by kkhider** [comment]
A noter que j'ai ajouté un médecin sur secteur Oran - Canastel via Rep qui a le secteur d'alger (pas logique). Mais j'ai souhaité voir le résultat jusqu'au bout

**Comment by kkhider** [comment]
Meme opération d'ajout via Rep Sonia mais cette fois en respectant le secteur du Rep à savoir ajout médecin sur secteur Alger et sous secteur Ain Taya . Demande enregistré. Sauf que sur interface admin le problème d'approbation persiste . Donc ce bug n'a rien à voir avec le choix de secteur qui n'est pas celui du Rep 
![image](https://user-images.githubusercontent.com/41648667/47356310-f3ad7c80-d6c3-11e8-861c-bd2dbc37ff3b.png)

**Comment by akqira** [comment]
will be fixed today

**Comment by akqira** [comment]
Fixed
