### ISSUE TITLE
Erreur campagnes de segmentation listées 

### ISSUE THREAD

**Issue by kkhider** [akqira/RepRep#6]
J'ai crée une campagne dont le nombre de formulaires est tombé à 18 ce qui est logique étant donnée que j'ai fait 18 PM . 
Les historiques campagnes ont été automatiquement changés à 18 formulaires !  
Les anciennes Matrices devraient être figées puisque c'est un historique ! voir pourquoi cela se passe

**Comment by akqira** [comment]
Done
