### ISSUE TITLE
Process ajout nouveau PM 

### ISSUE THREAD

**Issue by kkhider** [akqira/RepRep#62]
Rep Sonia : J'ai ajouté un médecin Kadri Mohamed Cabinet de group - Anatomie pathologique - Alger - Ain Taya - J'approuve la requete dans Admin - Je reviens vers interface Sonia et je veux planifier le médecin pour une visite - je cherche d'abord dans la base de donnée - le médecin y est - je vais dans planification je le trouve aussi mais en tant qu'INNACTIF !! Pourquoi ??

**Comment by akqira** [comment]
aucune idée. Je reproduis à mon niveau pour test

**Comment by akqira** [comment]
Je viens de trouver. Alors le médecin étant nouvellement ajouté il n'a pas de fréquence de visite définie
Si tu va sur l'écran de définition de fréquence, il n'en n'a pas. Faut donc lui attribuer une fréquence et hop, il sera sur la planification

**Comment by kkhider** [comment]
d'accord !! mais les fréquences ne se définissent qu'avant un cycle ( valable pour cycle suivant) non?

**Comment by kkhider** [comment]
c'est bon planification autorisée

**Comment by akqira** [comment]
Réponse sur l'issue #63
