### ISSUE TITLE
Cycle non définit et -1% de progression

### ISSUE THREAD

**Issue by kkhider** [akqira/RepRep#64]
Ca correspond à quoi le -1%???
![image](https://user-images.githubusercontent.com/41648667/47846818-838cae00-ddc9-11e8-8758-983cfe606562.png)

**Comment by akqira** [comment]
Quand il ne trouve aucun cycle défini et que le système n'a aucune progression à calculer il retourne -1
Je pense que je vais plutot mettre un texte comme avant : aucun objectif !!!!

**Comment by kkhider** [comment]
Oui pour etre clair ; je prépare la formation users par interface aujourdhui

**Comment by akqira** [comment]
fixed
