### ISSUE TITLE
Bugs sur tous les modules

### ISSUE THREAD

**Issue by kkhider** [akqira/RepRep#67]
Cycle débute aujourdhui 06 Novembre et bugs un peu partout ; why??
![image](https://user-images.githubusercontent.com/41648667/48092118-05d30300-e20c-11e8-8949-2ddb587098b3.png)

**Comment by akqira** [comment]
fixed. cause du probleme : chevauchement de cycle. Je vais creer une issue de type bug pour que l'application controle le chevauchement de cycle si jamais il y'en a
