### ISSUE TITLE
Filtre secteur ne réinitialise pas les données quand on repasse à TOUS

### ISSUE THREAD

**Issue by akqira** [akqira/RepRep#69]
Scénario de test : on affiche la liste des PM, on filtre sur un secteur puis sous secteur. on a le résultat attendu, mais quand le filtre secteur est remis à la valeur TOUS, il n'y a pas de raffrachissement des données malgré que le secteur = TOUS et sous secteur = TOUS.
Action à faire : Recharger les données si le filtre secteur = TOUS

**Comment by kkhider** [comment]
ok, important point , merci

**Comment by akqira** [comment]
Fixed
