### ISSUE TITLE
bug filtre PM Liste des requetes 

### ISSUE THREAD

**Issue by akqira** [akqira/RepRep#85]
![issue](https://user-images.githubusercontent.com/28217846/48304842-12639e00-e521-11e8-8510-68dc677bf5fe.PNG)

**Comment by kkhider** [comment]
!!!

**Comment by akqira** [comment]
Fixed. Explications : 
Le médecin que j'ai tenté d'ajouter était sans NOM ni PRENOM ce qui explique null null, cette issue sera reglée automatiquement avec l'issue #88 
Je le cloture donc
