### ISSUE TITLE
Plannif - Samedi visites planifiées or c'est paramétré comme étant un WE

### ISSUE THREAD

**Issue by kkhider** [akqira/RepRep#90]
![image](https://user-images.githubusercontent.com/41648667/48538034-a338d180-e8b3-11e8-8b97-4b0c98d85b84.png)

**Comment by akqira** [comment]
Déjà planifié dans une autre issue. Noté

**Comment by kkhider** [comment]
noté, idem pour les jours fériés

**Comment by akqira** [comment]
fixed pour weekend, not yet pour férié. Je vais créer une issue différente pour ça
