### ISSUE TITLE
Filtres

### ISSUE THREAD

**Issue by kkhider** [akqira/RepRep#93]
quand je paramètre un filtre sur expl planification, la selection filtre s'enregistre sur les autres modules ( BD, requete, rapport) . Pourquoi? cela devrait etre séparés 
![image](https://user-images.githubusercontent.com/41648667/48542849-7e972680-e8c0-11e8-8888-011a9dfad9eb.png)

**Comment by akqira** [comment]
C'est une sauvegarde volontaire, quand tu bosse sur une population par exemple c'est plus pratique de retrouver cette même population dans les différents ecrans.
On peut les séparer bien entendu, à toi de décider

**Comment by kkhider** [comment]
oui stp , on sépare; en pratique c'est pas évident à gérer en fait !! merci

**Comment by akqira** [comment]
Fixed. 
Si on filtre dans l'écran planification ça n'a aucune incidence sur le filtre des autres écrans

**Comment by kkhider** [comment]
great, closed donc , merci
