### ISSUE TITLE
Agenda historique visites

### ISSUE THREAD

**Issue by kkhider** [akqira/RepRep#98]
Salwa khider Agenda visites avec rapports mardi 20 ; les médecins n'ont pas d'historique de visites pourtant ils sont répertoriés en tant que visites faites aves rapports ; je suppose que c'est en cours

![image](https://user-images.githubusercontent.com/41648667/48689505-2a938700-ebcb-11e8-8128-5c88f2a5159e.png)

**Comment by kkhider** [comment]
![image](https://user-images.githubusercontent.com/41648667/48689564-6fb7b900-ebcb-11e8-9b6b-7c8af1107d9b.png)

**Comment by akqira** [comment]
oui exact. nettoyage en cours des transferts de données (triche des données)

**Comment by akqira** [comment]
fixed
